import { TravelProduct } from './types';

// 모든 가격은 인천 출발 기준 항공 왕복 + 숙박 패키지 가격 기준
// Trip.com URL 형식 (날짜는 RecommendationList에서 동적으로 추가):
// /packages/list?aCityCode={IATA}&dCityCode=SEL&tripWay=round-trip&classType=ys
//   &room=1&adult=1&child=0&infants=0
//   &destinationName={EN_NAME}&isOversea=true
//   &locale=ko-KR&curr=KRW
//   &AllianceId=8110614&SID=307168163&trip_sub1={id}&trip_sub3=D15747636
// dDate / rDate 는 buildTripUrl() 에서 +1달 기준으로 동적 생성

const BASE = 'https://kr.trip.com/packages/list';
const ALLIANCE_ID = '8110614';
const SID = '307168163';
const SUB3 = 'D15747636';

function tripUrl(aCityCode: string, destinationName: string, id: string): string {
  return (
    `${BASE}?adult=1&child=0&infants=0` +
    `&aCityCode=${aCityCode}&dCityCode=SEL` +
    `&tripWay=round-trip&classType=ys&room=1` +
    `&destinationName=${encodeURIComponent(destinationName)}` +
    `&isOversea=true&locale=ko-KR&curr=KRW` +
    `&AllianceId=${ALLIANCE_ID}&SID=${SID}&trip_sub1=${id}&trip_sub3=${SUB3}`
  );
}

export const products: TravelProduct[] = [

  // ══════════════════════════════════════════
  // 힐링 여행자 (healer)
  // ══════════════════════════════════════════
  {
    id: 'h1',
    title: '다낭 3박5일 리조트 패키지 (항공+숙박)',
    destination: '다낭',
    price: 720000,
    priceRange: 'budget',
    imageEmoji: '🏖️',
    description: '인천↔다낭 왕복 항공 + 미케비치 3성 리조트 3박, 스파 1회 포함',
    tripComUrl: tripUrl('DAD', 'Danang', 'h1'),
    nights: 3,
    rating: 4.6,
    personalityTypes: ['healer'],
    tags: ['힐링', '다낭', '항공포함'],
  },
  {
    id: 'h2',
    title: '오키나와 3박4일 힐링 패키지 (항공+숙박)',
    destination: '오키나와',
    price: 850000,
    priceRange: 'budget',
    imageEmoji: '🌺',
    description: '인천↔오키나와 왕복 항공 + 에메랄드 해변 비치 호텔 3박',
    tripComUrl: tripUrl('OKA', 'Okinawa', 'h2'),
    nights: 3,
    rating: 4.5,
    personalityTypes: ['healer'],
    tags: ['힐링', '오키나와', '항공포함'],
  },
  {
    id: 'h3',
    title: '발리 우붓 4박6일 스파 패키지 (항공+풀빌라)',
    destination: '발리',
    price: 1650000,
    priceRange: 'mid',
    imageEmoji: '🌴',
    description: '인천↔발리 왕복 항공 + 우붓 정글 뷰 풀빌라 4박 + 바디 스파 2회',
    tripComUrl: tripUrl('DPS', 'Bali', 'h3'),
    nights: 4,
    rating: 4.8,
    personalityTypes: ['healer'],
    tags: ['스파', '발리', '풀빌라'],
  },
  {
    id: 'h4',
    title: '보라카이 4박6일 비치 리조트 (항공+숙박)',
    destination: '보라카이',
    price: 1350000,
    priceRange: 'mid',
    imageEmoji: '🤍',
    description: '인천↔보라카이 왕복 항공 + 화이트비치 4성 리조트 4박',
    tripComUrl: tripUrl('MPH', 'Boracay', 'h4'),
    nights: 4,
    rating: 4.7,
    personalityTypes: ['healer'],
    tags: ['힐링', '보라카이', '리조트'],
  },
  {
    id: 'h5',
    title: '몰디브 오버워터 빌라 5박7일 (항공+올인클루시브)',
    destination: '몰디브',
    price: 4800000,
    priceRange: 'luxury',
    imageEmoji: '🐠',
    description: '인천↔몰디브 왕복 항공(경유) + 오버워터 빌라 5박 + 식사·스노클링 포함',
    tripComUrl: tripUrl('MLE', 'Maldives', 'h5'),
    nights: 5,
    rating: 4.9,
    personalityTypes: ['healer'],
    tags: ['럭셔리', '몰디브', '올인클루시브'],
  },
  {
    id: 'h6',
    title: '하와이 마우이 5박7일 럭셔리 패키지 (항공+5성)',
    destination: '하와이',
    price: 3800000,
    priceRange: 'luxury',
    imageEmoji: '🌺',
    description: '인천↔호놀룰루 왕복 항공 + 마우이 5성급 리조트 5박 + 조식 포함',
    tripComUrl: tripUrl('HNL', 'Hawaii', 'h6'),
    nights: 5,
    rating: 4.8,
    personalityTypes: ['healer'],
    tags: ['럭셔리', '하와이', '리조트'],
  },

  // ══════════════════════════════════════════
  // 모험 탐험가 (adventurer)
  // ══════════════════════════════════════════
  {
    id: 'a1',
    title: '세부 3박5일 다이빙+아일랜드호핑 (항공+숙박)',
    destination: '세부',
    price: 780000,
    priceRange: 'budget',
    imageEmoji: '🤿',
    description: '인천↔세부 왕복 항공 + 3성 리조트 3박 + 아일랜드호핑·고래상어 투어',
    tripComUrl: tripUrl('CEB', 'Cebu', 'a1'),
    nights: 3,
    rating: 4.7,
    personalityTypes: ['adventurer'],
    tags: ['액티비티', '세부', '다이빙'],
  },
  {
    id: 'a2',
    title: '치앙마이 3박5일 트레킹+엘리펀트 (항공+숙박)',
    destination: '치앙마이',
    price: 690000,
    priceRange: 'budget',
    imageEmoji: '🐘',
    description: '인천↔치앙마이 왕복 항공 + 3성 호텔 3박 + 정글 트레킹·코끼리 체험',
    tripComUrl: tripUrl('CNX', 'Chiang Mai', 'a2'),
    nights: 3,
    rating: 4.6,
    personalityTypes: ['adventurer'],
    tags: ['트레킹', '치앙마이', '액티비티'],
  },
  {
    id: 'a3',
    title: '호주 케언즈 5박7일 어드벤처 (항공+숙박)',
    destination: '케언즈',
    price: 2100000,
    priceRange: 'mid',
    imageEmoji: '🪂',
    description: '인천↔케언즈 왕복 항공 + 중급 호텔 5박 + 스카이다이빙·번지점프·그레이트배리어리프 스쿠버 포함',
    tripComUrl: tripUrl('CNS', 'Cairns', 'a3'),
    nights: 5,
    rating: 4.9,
    personalityTypes: ['adventurer'],
    tags: ['극한스포츠', '호주', '스카이다이빙'],
  },
  {
    id: 'a4',
    title: '홋카이도 설원+유빙 5박7일 (항공+숙박)',
    destination: '홋카이도',
    price: 1350000,
    priceRange: 'mid',
    imageEmoji: '🧊',
    description: '인천↔신치토세 왕복 항공 + 삿포로·아바시리 5박 + 유빙 크루즈·설산 스키 1일권 포함',
    tripComUrl: tripUrl('CTS', 'Hokkaido', 'a4'),
    nights: 5,
    rating: 4.8,
    personalityTypes: ['adventurer'],
    tags: ['겨울여행', '홋카이도', '유빙'],
  },
  {
    id: 'a5',
    title: '구채구+황룡 5박7일 트레킹 패키지 (항공+숙박)',
    destination: '구채구',
    price: 2800000,
    priceRange: 'luxury',
    imageEmoji: '🏔️',
    description: '인천↔청두 왕복 항공 + 구채구·황룡 5박 (프라이빗 가이드·전용차 포함) + 판다기지 방문',
    tripComUrl: tripUrl('CTU', 'Chengdu', 'a5'),
    nights: 5,
    rating: 4.9,
    personalityTypes: ['adventurer'],
    tags: ['트레킹', '중국', '구채구'],
  },
  {
    id: 'a6',
    title: '호주 시드니+케언즈 8박10일 럭셔리 (항공+숙박)',
    destination: '시드니',
    price: 4500000,
    priceRange: 'luxury',
    imageEmoji: '🦘',
    description: '인천↔시드니 왕복 항공 + 시드니 4박·케언즈 4박 5성 호텔 + 그레이트배리어리프 헬기투어·아웃백 사파리',
    tripComUrl: tripUrl('SYD', 'Sydney', 'a6'),
    nights: 8,
    rating: 4.8,
    personalityTypes: ['adventurer'],
    tags: ['호주', '그레이트배리어리프', '럭셔리'],
  },

  // ══════════════════════════════════════════
  // 감성 로맨티스트 (romantic)
  // ══════════════════════════════════════════
  {
    id: 'r1',
    title: '교토·오사카 3박4일 감성 패키지 (항공+숙박)',
    destination: '교토',
    price: 750000,
    priceRange: 'budget',
    imageEmoji: '⛩️',
    description: '인천↔오사카 왕복 항공 + 교토 감성 료칸 2박 + 오사카 호텔 1박',
    tripComUrl: tripUrl('KIX', 'Osaka', 'r1'),
    nights: 3,
    rating: 4.7,
    personalityTypes: ['romantic'],
    tags: ['감성', '교토', '료칸'],
  },
  {
    id: 'r2',
    title: '후쿠오카 2박3일 야경+온천 패키지 (항공+숙박)',
    destination: '후쿠오카',
    price: 590000,
    priceRange: 'budget',
    imageEmoji: '🌃',
    description: '인천↔후쿠오카 왕복 항공 + 야타이 거리 인근 호텔 2박 + 유후인 온천 당일치기',
    tripComUrl: tripUrl('FUK', 'Fukuoka', 'r2'),
    nights: 2,
    rating: 4.5,
    personalityTypes: ['romantic'],
    tags: ['야경', '후쿠오카', '온천'],
  },
  {
    id: 'r3',
    title: '프라하+비엔나 5박7일 감성 유럽 (항공+숙박)',
    destination: '프라하',
    price: 1950000,
    priceRange: 'mid',
    imageEmoji: '🏰',
    description: '인천↔프라하 왕복 항공 + 프라하 3박·비엔나 2박 감성 부티크 호텔',
    tripComUrl: tripUrl('PRG', 'Prague', 'r3'),
    nights: 5,
    rating: 4.8,
    personalityTypes: ['romantic'],
    tags: ['유럽', '프라하', '감성'],
  },
  {
    id: 'r4',
    title: '포르투갈 리스본+포르투 5박7일 (항공+숙박)',
    destination: '포르투',
    price: 1850000,
    priceRange: 'mid',
    imageEmoji: '🍷',
    description: '인천↔리스본 왕복 항공 + 리스본 3박·포르투 2박 + 와이너리 투어',
    tripComUrl: tripUrl('LIS', 'Lisbon', 'r4'),
    nights: 5,
    rating: 4.7,
    personalityTypes: ['romantic'],
    tags: ['유럽', '포르투갈', '와인'],
  },
  {
    id: 'r5',
    title: '파리+몽생미셸 6박8일 럭셔리 (항공+5성)',
    destination: '파리',
    price: 3600000,
    priceRange: 'luxury',
    imageEmoji: '🗼',
    description: '인천↔파리 왕복 항공(직항) + 파리 5성 호텔 5박 + 에펠탑 디너·루브르 야간 투어',
    tripComUrl: tripUrl('CDG', 'Paris', 'r5'),
    nights: 6,
    rating: 4.9,
    personalityTypes: ['romantic'],
    tags: ['럭셔리', '파리', '5성호텔'],
  },
  {
    id: 'r6',
    title: '산토리니+미코노스 7박9일 (항공+선셋빌라)',
    destination: '산토리니',
    price: 4200000,
    priceRange: 'luxury',
    imageEmoji: '🌅',
    description: '인천↔아테네 왕복 항공 + 산토리니 이아 선셋뷰 빌라 4박·미코노스 3박',
    tripComUrl: tripUrl('ATH', 'Athens', 'r6'),
    nights: 7,
    rating: 4.9,
    personalityTypes: ['romantic'],
    tags: ['럭셔리', '그리스', '산토리니'],
  },

  // ══════════════════════════════════════════
  // 자유로운 방랑자 (wanderer)
  // ══════════════════════════════════════════
  {
    id: 'w1',
    title: '방콕+파타야 4박5일 자유여행 (항공+숙박)',
    destination: '방콕',
    price: 650000,
    priceRange: 'budget',
    imageEmoji: '🛺',
    description: '인천↔방콕 왕복 항공 + 카오산로드 게스트하우스 2박·파타야 2박',
    tripComUrl: tripUrl('BKK', 'Bangkok', 'w1'),
    nights: 4,
    rating: 4.5,
    personalityTypes: ['wanderer'],
    tags: ['자유여행', '방콕', '배낭'],
  },
  {
    id: 'w2',
    title: '하노이+하롱베이 3박5일 자유여행 (항공+숙박)',
    destination: '하노이',
    price: 720000,
    priceRange: 'budget',
    imageEmoji: '🏍️',
    description: '인천↔하노이 왕복 항공 + 올드쿼터 호텔 2박 + 하롱베이 크루즈 1박',
    tripComUrl: tripUrl('HAN', 'Hanoi', 'w2'),
    nights: 3,
    rating: 4.6,
    personalityTypes: ['wanderer'],
    tags: ['자유여행', '하노이', '하롱베이'],
  },
  {
    id: 'w3',
    title: '바르셀로나+마드리드 6박8일 자유여행 (항공+숙박)',
    destination: '바르셀로나',
    price: 2000000,
    priceRange: 'mid',
    imageEmoji: '🎭',
    description: '인천↔바르셀로나 왕복 항공 + 바르셀로나 3박·마드리드 3박 중급 호텔',
    tripComUrl: tripUrl('BCN', 'Barcelona', 'w3'),
    nights: 6,
    rating: 4.7,
    personalityTypes: ['wanderer'],
    tags: ['유럽', '바르셀로나', '자유여행'],
  },
  {
    id: 'w4',
    title: '리스본+세비야 5박7일 자유여행 (항공+숙박)',
    destination: '리스본',
    price: 1900000,
    priceRange: 'mid',
    imageEmoji: '🚃',
    description: '인천↔리스본 왕복 항공 + 리스본 3박·세비야 2박 부티크 호스텔·호텔',
    tripComUrl: tripUrl('LIS', 'Lisbon', 'w4'),
    nights: 5,
    rating: 4.6,
    personalityTypes: ['wanderer'],
    tags: ['유럽', '리스본', '자유여행'],
  },
  {
    id: 'w5',
    title: '두바이+아부다비 5박7일 자유여행 (항공+숙박)',
    destination: '두바이',
    price: 2800000,
    priceRange: 'luxury',
    imageEmoji: '🏜️',
    description: '인천↔두바이 왕복 항공 + 두바이 4박·아부다비 1박 + 사막 사파리·골드수크 투어·버즈칼리파 전망대',
    tripComUrl: tripUrl('DXB', 'Dubai', 'w5'),
    nights: 5,
    rating: 4.8,
    personalityTypes: ['wanderer'],
    tags: ['두바이', '사막사파리', '자유여행'],
  },
  {
    id: 'w6',
    title: '인도 황금삼각지대+고아 8박10일 (항공+숙박)',
    destination: '인도',
    price: 3800000,
    priceRange: 'luxury',
    imageEmoji: '🕌',
    description: '인천↔델리 왕복 항공 + 델리·아그라·자이푸르·고아 8박 + 타지마할·야생동물 사파리 포함',
    tripComUrl: tripUrl('DEL', 'Delhi', 'w6'),
    nights: 8,
    rating: 4.7,
    personalityTypes: ['wanderer'],
    tags: ['인도', '타지마할', '자유여행'],
  },

  // ══════════════════════════════════════════
  // 완벽한 계획가 (planner)
  // ══════════════════════════════════════════
  {
    id: 'p1',
    title: '도쿄 3박4일 완벽 가이드투어 (항공+숙박)',
    destination: '도쿄',
    price: 850000,
    priceRange: 'budget',
    imageEmoji: '🗼',
    description: '인천↔도쿄 왕복 항공 + 신주쿠 3성 호텔 3박 + 주요 명소 가이드투어 1일',
    tripComUrl: tripUrl('NRT', 'Tokyo', 'p1'),
    nights: 3,
    rating: 4.6,
    personalityTypes: ['planner'],
    tags: ['패키지', '도쿄', '가이드'],
  },
  {
    id: 'p2',
    title: '싱가포르 3박5일 올인원 패키지 (항공+숙박)',
    destination: '싱가포르',
    price: 950000,
    priceRange: 'budget',
    imageEmoji: '🦁',
    description: '인천↔싱가포르 왕복 항공 + 4성 호텔 3박 + 유니버셜·마리나베이샌즈 입장권',
    tripComUrl: tripUrl('SIN', 'Singapore', 'p2'),
    nights: 3,
    rating: 4.7,
    personalityTypes: ['planner'],
    tags: ['패키지', '싱가포르', '가이드'],
  },
  {
    id: 'p3',
    title: '일본 간사이 JR패스 5박7일 (항공+숙박)',
    destination: '오사카·교토',
    price: 1450000,
    priceRange: 'mid',
    imageEmoji: '🚅',
    description: '인천↔오사카 왕복 항공 + JR패스 7일권 + 준특급 호텔 5박 (교토·나라·고베 포함)',
    tripComUrl: tripUrl('KIX', 'Osaka', 'p3'),
    nights: 5,
    rating: 4.8,
    personalityTypes: ['planner'],
    tags: ['패키지', '일본', 'JR패스'],
  },
  {
    id: 'p4',
    title: '런던+파리 6박8일 유럽 2개국 (항공+숙박)',
    destination: '런던·파리',
    price: 2400000,
    priceRange: 'mid',
    imageEmoji: '🎡',
    description: '인천↔런던 왕복 항공 + 런던 3박·유로스타·파리 3박 4성 호텔',
    tripComUrl: tripUrl('LHR', 'London', 'p4'),
    nights: 6,
    rating: 4.7,
    personalityTypes: ['planner'],
    tags: ['유럽', '런던', '파리'],
  },
  {
    id: 'p5',
    title: '유럽 4개국 12박14일 프리미엄 투어 (항공+숙박)',
    destination: '유럽',
    price: 5200000,
    priceRange: 'luxury',
    imageEmoji: '🗺️',
    description: '인천↔로마 왕복 항공(직항) + 이탈리아·스위스·프랑스·스페인 5성급 호텔 12박',
    tripComUrl: tripUrl('FCO', 'Rome', 'p5'),
    nights: 12,
    rating: 4.9,
    personalityTypes: ['planner'],
    tags: ['럭셔리', '유럽', '패키지'],
  },
  {
    id: 'p6',
    title: '지중해 크루즈 7박 (항공+크루즈)',
    destination: '지중해',
    price: 4500000,
    priceRange: 'luxury',
    imageEmoji: '🚢',
    description: '인천↔바르셀로나 왕복 항공 + MSC 크루즈 7박 (로마·나폴리·마르세유 기항)',
    tripComUrl: tripUrl('BCN', 'Barcelona', 'p6'),
    nights: 7,
    rating: 4.8,
    personalityTypes: ['planner'],
    tags: ['크루즈', '지중해', '럭셔리'],
  },

  // ══════════════════════════════════════════
  // 미식 탐험가 (gourmet)
  // ══════════════════════════════════════════
  {
    id: 'g1',
    title: '오사카 3박4일 미식 탐방 (항공+숙박)',
    destination: '오사카',
    price: 780000,
    priceRange: 'budget',
    imageEmoji: '🍣',
    description: '인천↔오사카 왕복 항공 + 도톤보리 근처 호텔 3박 + 쿠킹클래스 1회',
    tripComUrl: tripUrl('KIX', 'Osaka', 'g1'),
    nights: 3,
    rating: 4.7,
    personalityTypes: ['gourmet'],
    tags: ['미식', '오사카', '쿠킹클래스'],
  },
  {
    id: 'g2',
    title: '홍콩 2박3일 딤섬·야경 미식 투어 (항공+숙박)',
    destination: '홍콩',
    price: 680000,
    priceRange: 'budget',
    imageEmoji: '🥟',
    description: '인천↔홍콩 왕복 항공 + 침사추이 4성 호텔 2박 + 딤섬 투어·야경 크루즈',
    tripComUrl: tripUrl('HKG', 'Hong Kong', 'g2'),
    nights: 2,
    rating: 4.6,
    personalityTypes: ['gourmet'],
    tags: ['미식', '홍콩', '딤섬'],
  },
  {
    id: 'g3',
    title: '이스탄불 4박6일 바자르+미식 (항공+숙박)',
    destination: '이스탄불',
    price: 1750000,
    priceRange: 'mid',
    imageEmoji: '🥙',
    description: '인천↔이스탄불 왕복 항공 + 올드시티 4성 호텔 4박 + 바자르 미식 투어·쿠킹클래스',
    tripComUrl: tripUrl('IST', 'Istanbul', 'g3'),
    nights: 4,
    rating: 4.7,
    personalityTypes: ['gourmet'],
    tags: ['미식', '이스탄불', '터키'],
  },
  {
    id: 'g4',
    title: '방콕 로컬 미식 5박6일 (항공+숙박)',
    destination: '방콕',
    price: 1100000,
    priceRange: 'mid',
    imageEmoji: '🍜',
    description: '인천↔방콕 왕복 항공 + 씰롬 4성 호텔 5박 + 야시장 미식 투어·타이쿠킹 클래스',
    tripComUrl: tripUrl('BKK', 'Bangkok', 'g4'),
    nights: 5,
    rating: 4.6,
    personalityTypes: ['gourmet'],
    tags: ['미식', '방콕', '태국음식'],
  },
  {
    id: 'g5',
    title: '나폴리+로마 7박9일 이탈리안 미식 (항공+숙박)',
    destination: '나폴리·로마',
    price: 3800000,
    priceRange: 'luxury',
    imageEmoji: '🍕',
    description: '인천↔로마 왕복 항공(직항) + 나폴리 3박·로마 4박 5성 호텔 + 피자·파스타 쿠킹 마스터클래스',
    tripComUrl: tripUrl('FCO', 'Rome', 'g5'),
    nights: 7,
    rating: 4.9,
    personalityTypes: ['gourmet'],
    tags: ['미식', '이탈리아', '쿠킹클래스'],
  },
  {
    id: 'g6',
    title: '도쿄 오마카세 미식 기행 5박7일 (항공+5성)',
    destination: '도쿄',
    price: 4200000,
    priceRange: 'luxury',
    imageEmoji: '🍱',
    description: '인천↔도쿄 왕복 항공(직항) + 긴자 5성 호텔 5박 + 미쉐린 오마카세 2회·도요스 시장 새벽투어',
    tripComUrl: tripUrl('NRT', 'Tokyo', 'g6'),
    nights: 5,
    rating: 4.9,
    personalityTypes: ['gourmet'],
    tags: ['미식', '도쿄', '오마카세'],
  },
];
