import { TravelProduct } from './types';

// 모든 가격은 인천 출발 기준 항공 왕복 + 숙박 패키지 가격 기준
// budget  : ~100만원   (근거리 아시아 3~4박, 이코노미 + 중급 호텔)
// mid     : 100~250만원 (중거리 아시아 4~6박 or 유럽 단거리, 이코노미 + 준특급)
// luxury  : 250만원~   (장거리 or 고급 리조트, 비즈니스 or 5성급)
//
// Trip.com 제휴 URL 패턴:
// https://www.trip.com/packages/list/seoul-to-{slug}/sel-to-{code}
//   ?dCity=sel&aCity={code}&AllianceId=8110614&SID=307168163&trip_sub1={id}&trip_sub3=D15747636

const ALLIANCE_ID = '8110614';
const SID = '307168163';
const SUB3 = 'D15747636';

function tripUrl(slug: string, code: string, id: string): string {
  return (
    `https://www.trip.com/packages/list/seoul-to-${slug}/sel-to-${code}` +
    `?dCity=sel&aCity=${code}&AllianceId=${ALLIANCE_ID}&SID=${SID}&trip_sub1=${id}&trip_sub3=${SUB3}`
  );
}

export const products: TravelProduct[] = [

  // ══════════════════════════════════════════
  // 힐링 여행자 (healer)
  // ══════════════════════════════════════════
  // budget ~100만원
  {
    id: 'h1',
    title: '다낭 3박5일 리조트 패키지 (항공+숙박)',
    destination: '다낭',
    price: 720000,
    priceRange: 'budget',
    imageEmoji: '🏖️',
    description: '인천↔다낭 왕복 항공 + 미케비치 3성 리조트 3박, 스파 1회 포함',
    myrealTripUrl: 'https://www.myrealtrip.com/search?q=다낭+리조트+패키지',
    tripComUrl: tripUrl('danang', 'dad', 'h1'),
    rating: 4.6,
    personalityTypes: ['healer'],
    tags: ['힐링', '다낭', '항공포함'],
  },
  {
    id: 'h2',
    title: '오키나와 3박4일 힐링 패키지 (항공+숙박)',
    destination: '오키나와',
    price: 850000,
    priceRange: 'budget',
    imageEmoji: '🌺',
    description: '인천↔오키나와 왕복 항공 + 에메랄드 해변 비치 호텔 3박',
    myrealTripUrl: 'https://www.myrealtrip.com/search?q=오키나와+힐링+패키지',
    tripComUrl: tripUrl('okinawa', 'oka', 'h2'),
    rating: 4.5,
    personalityTypes: ['healer'],
    tags: ['힐링', '오키나와', '항공포함'],
  },
  // mid 100~250만원
  {
    id: 'h3',
    title: '발리 우붓 4박6일 스파 패키지 (항공+풀빌라)',
    destination: '발리',
    price: 1650000,
    priceRange: 'mid',
    imageEmoji: '🌴',
    description: '인천↔발리 왕복 항공 + 우붓 정글 뷰 풀빌라 4박 + 바디 스파 2회',
    myrealTripUrl: 'https://www.myrealtrip.com/search?q=발리+풀빌라+스파+패키지',
    tripComUrl: tripUrl('bali', 'dps', 'h3'),
    rating: 4.8,
    personalityTypes: ['healer'],
    tags: ['스파', '발리', '풀빌라'],
  },
  {
    id: 'h4',
    title: '보라카이 4박6일 비치 리조트 (항공+숙박)',
    destination: '보라카이',
    price: 1350000,
    priceRange: 'mid',
    imageEmoji: '🤍',
    description: '인천↔보라카이 왕복 항공 + 화이트비치 4성 리조트 4박',
    myrealTripUrl: 'https://www.myrealtrip.com/search?q=보라카이+리조트+패키지',
    tripComUrl: tripUrl('boracay', 'mph', 'h4'),
    rating: 4.7,
    personalityTypes: ['healer'],
    tags: ['힐링', '보라카이', '리조트'],
  },
  // luxury 250만원~
  {
    id: 'h5',
    title: '몰디브 오버워터 빌라 5박7일 (항공+올인클루시브)',
    destination: '몰디브',
    price: 4800000,
    priceRange: 'luxury',
    imageEmoji: '🐠',
    description: '인천↔몰디브 왕복 항공(경유) + 오버워터 빌라 5박 + 식사·스노클링 포함',
    myrealTripUrl: 'https://www.myrealtrip.com/search?q=몰디브+오버워터+빌라+패키지',
    tripComUrl: tripUrl('maldives', 'mle', 'h5'),
    rating: 4.9,
    personalityTypes: ['healer'],
    tags: ['럭셔리', '몰디브', '올인클루시브'],
  },
  {
    id: 'h6',
    title: '하와이 마우이 5박7일 럭셔리 패키지 (항공+5성)',
    destination: '하와이',
    price: 3800000,
    priceRange: 'luxury',
    imageEmoji: '🌺',
    description: '인천↔호놀룰루 왕복 항공 + 마우이 5성급 리조트 5박 + 조식 포함',
    myrealTripUrl: 'https://www.myrealtrip.com/search?q=하와이+마우이+5성+패키지',
    tripComUrl: tripUrl('hawaii', 'hnl', 'h6'),
    rating: 4.8,
    personalityTypes: ['healer'],
    tags: ['럭셔리', '하와이', '리조트'],
  },

  // ══════════════════════════════════════════
  // 모험 탐험가 (adventurer)
  // ══════════════════════════════════════════
  // budget ~100만원
  {
    id: 'a1',
    title: '세부 3박5일 다이빙+아일랜드호핑 (항공+숙박)',
    destination: '세부',
    price: 780000,
    priceRange: 'budget',
    imageEmoji: '🤿',
    description: '인천↔세부 왕복 항공 + 3성 리조트 3박 + 아일랜드호핑·고래상어 투어',
    myrealTripUrl: 'https://www.myrealtrip.com/search?q=세부+다이빙+패키지',
    tripComUrl: tripUrl('cebu', 'ceb', 'a1'),
    rating: 4.7,
    personalityTypes: ['adventurer'],
    tags: ['액티비티', '세부', '다이빙'],
  },
  {
    id: 'a2',
    title: '치앙마이 3박5일 트레킹+엘리펀트 (항공+숙박)',
    destination: '치앙마이',
    price: 690000,
    priceRange: 'budget',
    imageEmoji: '🐘',
    description: '인천↔치앙마이 왕복 항공 + 3성 호텔 3박 + 정글 트레킹·코끼리 체험',
    myrealTripUrl: 'https://www.myrealtrip.com/search?q=치앙마이+트레킹+패키지',
    tripComUrl: tripUrl('chiang-mai', 'cnx', 'a2'),
    rating: 4.6,
    personalityTypes: ['adventurer'],
    tags: ['트레킹', '치앙마이', '액티비티'],
  },
  // mid 100~250만원
  {
    id: 'a3',
    title: '뉴질랜드 퀸즈타운 5박7일 어드벤처 (항공+숙박)',
    destination: '뉴질랜드',
    price: 2100000,
    priceRange: 'mid',
    imageEmoji: '🪂',
    description: '인천↔퀸즈타운 왕복 항공 + 중급 호텔 5박 + 번지점프·스카이다이빙 1회',
    myrealTripUrl: 'https://www.myrealtrip.com/search?q=뉴질랜드+퀸즈타운+어드벤처',
    tripComUrl: tripUrl('queenstown', 'zqn', 'a3'),
    rating: 4.9,
    personalityTypes: ['adventurer'],
    tags: ['극한스포츠', '뉴질랜드', '번지점프'],
  },
  {
    id: 'a4',
    title: '아이슬란드 5박7일 링로드+오로라 (항공+숙박)',
    destination: '아이슬란드',
    price: 2450000,
    priceRange: 'mid',
    imageEmoji: '🌋',
    description: '인천↔레이캬비크 왕복 항공(경유) + 링로드 5박 + 오로라 투어 포함',
    myrealTripUrl: 'https://www.myrealtrip.com/search?q=아이슬란드+링로드+오로라',
    tripComUrl: tripUrl('reykjavik', 'kef', 'a4'),
    rating: 4.8,
    personalityTypes: ['adventurer'],
    tags: ['오로라', '아이슬란드', '트레킹'],
  },
  // luxury 250만원~
  {
    id: 'a5',
    title: '네팔 에베레스트 베이스캠프 10박12일 (항공+가이드)',
    destination: '네팔',
    price: 3200000,
    priceRange: 'luxury',
    imageEmoji: '🏔️',
    description: '인천↔카트만두 왕복 항공 + EBC 트레킹 10박 (가이드·포터·숙식 포함)',
    myrealTripUrl: 'https://www.myrealtrip.com/search?q=네팔+에베레스트+베이스캠프+트레킹',
    tripComUrl: tripUrl('kathmandu', 'ktm', 'a5'),
    rating: 4.9,
    personalityTypes: ['adventurer'],
    tags: ['트레킹', '네팔', '에베레스트'],
  },
  {
    id: 'a6',
    title: '파타고니아 토레스델파이네 11박13일 (항공+올인클루시브)',
    destination: '칠레',
    price: 5500000,
    priceRange: 'luxury',
    imageEmoji: '🦅',
    description: '인천↔푼타아레나스 왕복 항공 + 파타고니아 트레킹 전용 숙소 11박 올인클루시브',
    myrealTripUrl: 'https://www.myrealtrip.com/search?q=파타고니아+트레킹+패키지',
    tripComUrl: tripUrl('punta-arenas', 'pmq', 'a6'),
    rating: 4.8,
    personalityTypes: ['adventurer'],
    tags: ['트레킹', '남미', '파타고니아'],
  },

  // ══════════════════════════════════════════
  // 감성 로맨티스트 (romantic)
  // ══════════════════════════════════════════
  // budget ~100만원
  {
    id: 'r1',
    title: '교토·오사카 3박4일 감성 패키지 (항공+숙박)',
    destination: '교토',
    price: 750000,
    priceRange: 'budget',
    imageEmoji: '⛩️',
    description: '인천↔오사카 왕복 항공 + 교토 감성 료칸 2박 + 오사카 호텔 1박',
    myrealTripUrl: 'https://www.myrealtrip.com/search?q=교토+오사카+감성+패키지',
    tripComUrl: tripUrl('osaka', 'kix', 'r1'),
    rating: 4.7,
    personalityTypes: ['romantic'],
    tags: ['감성', '교토', '료칸'],
  },
  {
    id: 'r2',
    title: '후쿠오카 2박3일 야경+온천 패키지 (항공+숙박)',
    destination: '후쿠오카',
    price: 590000,
    priceRange: 'budget',
    imageEmoji: '🌃',
    description: '인천↔후쿠오카 왕복 항공 + 야타이 거리 인근 호텔 2박 + 유후인 온천 당일치기',
    myrealTripUrl: 'https://www.myrealtrip.com/search?q=후쿠오카+야경+온천+패키지',
    tripComUrl: tripUrl('fukuoka', 'fuk', 'r2'),
    rating: 4.5,
    personalityTypes: ['romantic'],
    tags: ['야경', '후쿠오카', '온천'],
  },
  // mid 100~250만원
  {
    id: 'r3',
    title: '프라하+비엔나 5박7일 감성 유럽 (항공+숙박)',
    destination: '프라하',
    price: 1950000,
    priceRange: 'mid',
    imageEmoji: '🏰',
    description: '인천↔프라하 왕복 항공 + 프라하 3박·비엔나 2박 감성 부티크 호텔',
    myrealTripUrl: 'https://www.myrealtrip.com/search?q=프라하+비엔나+감성+패키지',
    tripComUrl: tripUrl('prague', 'prg', 'r3'),
    rating: 4.8,
    personalityTypes: ['romantic'],
    tags: ['유럽', '프라하', '감성'],
  },
  {
    id: 'r4',
    title: '포르투갈 리스본+포르투 5박7일 (항공+숙박)',
    destination: '포르투',
    price: 1850000,
    priceRange: 'mid',
    imageEmoji: '🍷',
    description: '인천↔리스본 왕복 항공 + 리스본 3박·포르투 2박 + 와이너리 투어',
    myrealTripUrl: 'https://www.myrealtrip.com/search?q=포르투갈+리스본+포르투+패키지',
    tripComUrl: tripUrl('lisbon', 'lis', 'r4'),
    rating: 4.7,
    personalityTypes: ['romantic'],
    tags: ['유럽', '포르투갈', '와인'],
  },
  // luxury 250만원~
  {
    id: 'r5',
    title: '파리+몽생미셸 6박8일 럭셔리 (항공+5성)',
    destination: '파리',
    price: 3600000,
    priceRange: 'luxury',
    imageEmoji: '🗼',
    description: '인천↔파리 왕복 항공(직항) + 파리 5성 호텔 5박 + 에펠탑 디너·루브르 야간 투어',
    myrealTripUrl: 'https://www.myrealtrip.com/search?q=파리+5성+럭셔리+패키지',
    tripComUrl: tripUrl('paris', 'par', 'r5'),
    rating: 4.9,
    personalityTypes: ['romantic'],
    tags: ['럭셔리', '파리', '5성호텔'],
  },
  {
    id: 'r6',
    title: '산토리니+미코노스 7박9일 (항공+선셋빌라)',
    destination: '산토리니',
    price: 4200000,
    priceRange: 'luxury',
    imageEmoji: '🌅',
    description: '인천↔아테네 왕복 항공 + 산토리니 이아 선셋뷰 빌라 4박·미코노스 3박',
    myrealTripUrl: 'https://www.myrealtrip.com/search?q=산토리니+미코노스+럭셔리+패키지',
    tripComUrl: tripUrl('athens', 'ath', 'r6'),
    rating: 4.9,
    personalityTypes: ['romantic'],
    tags: ['럭셔리', '그리스', '산토리니'],
  },

  // ══════════════════════════════════════════
  // 자유로운 방랑자 (wanderer)
  // ══════════════════════════════════════════
  // budget ~100만원
  {
    id: 'w1',
    title: '방콕+파타야 4박5일 자유여행 (항공+숙박)',
    destination: '방콕',
    price: 650000,
    priceRange: 'budget',
    imageEmoji: '🛺',
    description: '인천↔방콕 왕복 항공 + 카오산로드 게스트하우스 2박·파타야 2박',
    myrealTripUrl: 'https://www.myrealtrip.com/search?q=방콕+파타야+자유여행+패키지',
    tripComUrl: tripUrl('bangkok', 'bkk', 'w1'),
    rating: 4.5,
    personalityTypes: ['wanderer'],
    tags: ['자유여행', '방콕', '배낭'],
  },
  {
    id: 'w2',
    title: '하노이+하롱베이 3박5일 자유여행 (항공+숙박)',
    destination: '하노이',
    price: 720000,
    priceRange: 'budget',
    imageEmoji: '🏍️',
    description: '인천↔하노이 왕복 항공 + 올드쿼터 호텔 2박 + 하롱베이 크루즈 1박',
    myrealTripUrl: 'https://www.myrealtrip.com/search?q=하노이+하롱베이+자유여행+패키지',
    tripComUrl: tripUrl('hanoi', 'han', 'w2'),
    rating: 4.6,
    personalityTypes: ['wanderer'],
    tags: ['자유여행', '하노이', '하롱베이'],
  },
  // mid 100~250만원
  {
    id: 'w3',
    title: '바르셀로나+마드리드 6박8일 자유여행 (항공+숙박)',
    destination: '바르셀로나',
    price: 2000000,
    priceRange: 'mid',
    imageEmoji: '🎭',
    description: '인천↔바르셀로나 왕복 항공 + 바르셀로나 3박·마드리드 3박 중급 호텔',
    myrealTripUrl: 'https://www.myrealtrip.com/search?q=바르셀로나+마드리드+자유여행',
    tripComUrl: tripUrl('barcelona', 'bcn', 'w3'),
    rating: 4.7,
    personalityTypes: ['wanderer'],
    tags: ['유럽', '바르셀로나', '자유여행'],
  },
  {
    id: 'w4',
    title: '리스본+세비야 5박7일 자유여행 (항공+숙박)',
    destination: '리스본',
    price: 1900000,
    priceRange: 'mid',
    imageEmoji: '🚃',
    description: '인천↔리스본 왕복 항공 + 리스본 3박·세비야 2박 부티크 호스텔·호텔',
    myrealTripUrl: 'https://www.myrealtrip.com/search?q=리스본+세비야+자유여행+패키지',
    tripComUrl: tripUrl('lisbon', 'lis', 'w4'),
    rating: 4.6,
    personalityTypes: ['wanderer'],
    tags: ['유럽', '리스본', '자유여행'],
  },
  // luxury 250만원~
  {
    id: 'w5',
    title: '모로코 마라케시+사하라 8박10일 (항공+글램핑)',
    destination: '모로코',
    price: 3500000,
    priceRange: 'luxury',
    imageEmoji: '🐪',
    description: '인천↔마라케시 왕복 항공(경유) + 마라케시 리야드 5박 + 사하라 럭셔리 글램핑 2박',
    myrealTripUrl: 'https://www.myrealtrip.com/search?q=모로코+사하라+글램핑+패키지',
    tripComUrl: tripUrl('marrakech', 'rak', 'w5'),
    rating: 4.8,
    personalityTypes: ['wanderer'],
    tags: ['모로코', '사하라', '글램핑'],
  },
  {
    id: 'w6',
    title: '남미 페루+볼리비아 10박12일 (항공+숙박)',
    destination: '페루',
    price: 4800000,
    priceRange: 'luxury',
    imageEmoji: '🌎',
    description: '인천↔리마 왕복 항공 + 마추픽추·우유니 소금사막 등 10박 올인클루시브',
    myrealTripUrl: 'https://www.myrealtrip.com/search?q=페루+볼리비아+마추픽추+패키지',
    tripComUrl: tripUrl('lima', 'lim', 'w6'),
    rating: 4.8,
    personalityTypes: ['wanderer'],
    tags: ['남미', '마추픽추', '우유니'],
  },

  // ══════════════════════════════════════════
  // 완벽한 계획가 (planner)
  // ══════════════════════════════════════════
  // budget ~100만원
  {
    id: 'p1',
    title: '도쿄 3박4일 완벽 가이드투어 (항공+숙박)',
    destination: '도쿄',
    price: 850000,
    priceRange: 'budget',
    imageEmoji: '🗼',
    description: '인천↔도쿄 왕복 항공 + 신주쿠 3성 호텔 3박 + 주요 명소 가이드투어 1일',
    myrealTripUrl: 'https://www.myrealtrip.com/search?q=도쿄+가이드투어+패키지',
    tripComUrl: tripUrl('tokyo', 'nrt', 'p1'),
    rating: 4.6,
    personalityTypes: ['planner'],
    tags: ['패키지', '도쿄', '가이드'],
  },
  {
    id: 'p2',
    title: '싱가포르 3박5일 올인원 패키지 (항공+숙박)',
    destination: '싱가포르',
    price: 950000,
    priceRange: 'budget',
    imageEmoji: '🦁',
    description: '인천↔싱가포르 왕복 항공 + 4성 호텔 3박 + 유니버셜·마리나베이샌즈 입장권',
    myrealTripUrl: 'https://www.myrealtrip.com/search?q=싱가포르+올인원+패키지',
    tripComUrl: tripUrl('singapore', 'sin', 'p2'),
    rating: 4.7,
    personalityTypes: ['planner'],
    tags: ['패키지', '싱가포르', '가이드'],
  },
  // mid 100~250만원
  {
    id: 'p3',
    title: '일본 간사이 JR패스 5박7일 (항공+숙박)',
    destination: '오사카·교토',
    price: 1450000,
    priceRange: 'mid',
    imageEmoji: '🚅',
    description: '인천↔오사카 왕복 항공 + JR패스 7일권 + 준특급 호텔 5박 (교토·나라·고베 포함)',
    myrealTripUrl: 'https://www.myrealtrip.com/search?q=일본+간사이+JR패스+패키지',
    tripComUrl: tripUrl('osaka', 'kix', 'p3'),
    rating: 4.8,
    personalityTypes: ['planner'],
    tags: ['패키지', '일본', 'JR패스'],
  },
  {
    id: 'p4',
    title: '런던+파리 6박8일 유럽 2개국 (항공+숙박)',
    destination: '런던·파리',
    price: 2400000,
    priceRange: 'mid',
    imageEmoji: '🎡',
    description: '인천↔런던 왕복 항공 + 런던 3박·유로스타·파리 3박 4성 호텔',
    myrealTripUrl: 'https://www.myrealtrip.com/search?q=런던+파리+유럽+패키지',
    tripComUrl: tripUrl('london', 'lhr', 'p4'),
    rating: 4.7,
    personalityTypes: ['planner'],
    tags: ['유럽', '런던', '파리'],
  },
  // luxury 250만원~
  {
    id: 'p5',
    title: '유럽 4개국 12박14일 프리미엄 투어 (항공+숙박)',
    destination: '유럽',
    price: 5200000,
    priceRange: 'luxury',
    imageEmoji: '🗺️',
    description: '인천↔로마 왕복 항공(직항) + 이탈리아·스위스·프랑스·스페인 5성급 호텔 12박',
    myrealTripUrl: 'https://www.myrealtrip.com/search?q=유럽+4개국+프리미엄+투어',
    tripComUrl: tripUrl('rome', 'fco', 'p5'),
    rating: 4.9,
    personalityTypes: ['planner'],
    tags: ['럭셔리', '유럽', '패키지'],
  },
  {
    id: 'p6',
    title: '지중해 크루즈 7박 (항공+크루즈)',
    destination: '지중해',
    price: 4500000,
    priceRange: 'luxury',
    imageEmoji: '🚢',
    description: '인천↔바르셀로나 왕복 항공 + MSC 크루즈 7박 (로마·나폴리·마르세유 기항)',
    myrealTripUrl: 'https://www.myrealtrip.com/search?q=지중해+크루즈+패키지',
    tripComUrl: tripUrl('barcelona', 'bcn', 'p6'),
    rating: 4.8,
    personalityTypes: ['planner'],
    tags: ['크루즈', '지중해', '럭셔리'],
  },

  // ══════════════════════════════════════════
  // 미식 탐험가 (gourmet)
  // ══════════════════════════════════════════
  // budget ~100만원
  {
    id: 'g1',
    title: '오사카 3박4일 미식 탐방 (항공+숙박)',
    destination: '오사카',
    price: 780000,
    priceRange: 'budget',
    imageEmoji: '🍣',
    description: '인천↔오사카 왕복 항공 + 도톤보리 근처 호텔 3박 + 쿠킹클래스 1회',
    myrealTripUrl: 'https://www.myrealtrip.com/search?q=오사카+미식+쿠킹클래스+패키지',
    tripComUrl: tripUrl('osaka', 'kix', 'g1'),
    rating: 4.7,
    personalityTypes: ['gourmet'],
    tags: ['미식', '오사카', '쿠킹클래스'],
  },
  {
    id: 'g2',
    title: '홍콩 2박3일 딤섬·야경 미식 투어 (항공+숙박)',
    destination: '홍콩',
    price: 680000,
    priceRange: 'budget',
    imageEmoji: '🥟',
    description: '인천↔홍콩 왕복 항공 + 침사추이 4성 호텔 2박 + 딤섬 투어·야경 크루즈',
    myrealTripUrl: 'https://www.myrealtrip.com/search?q=홍콩+딤섬+미식+투어+패키지',
    tripComUrl: tripUrl('hong-kong', 'hkg', 'g2'),
    rating: 4.6,
    personalityTypes: ['gourmet'],
    tags: ['미식', '홍콩', '딤섬'],
  },
  // mid 100~250만원
  {
    id: 'g3',
    title: '이스탄불 4박6일 바자르+미식 (항공+숙박)',
    destination: '이스탄불',
    price: 1750000,
    priceRange: 'mid',
    imageEmoji: '🥙',
    description: '인천↔이스탄불 왕복 항공 + 올드시티 4성 호텔 4박 + 바자르 미식 투어·쿠킹클래스',
    myrealTripUrl: 'https://www.myrealtrip.com/search?q=이스탄불+미식+쿠킹클래스+패키지',
    tripComUrl: tripUrl('istanbul', 'ist', 'g3'),
    rating: 4.7,
    personalityTypes: ['gourmet'],
    tags: ['미식', '이스탄불', '터키'],
  },
  {
    id: 'g4',
    title: '방콕 로컬 미식 5박6일 (항공+숙박)',
    destination: '방콕',
    price: 1100000,
    priceRange: 'mid',
    imageEmoji: '🍜',
    description: '인천↔방콕 왕복 항공 + 씰롬 4성 호텔 5박 + 야시장 미식 투어·타이쿠킹 클래스',
    myrealTripUrl: 'https://www.myrealtrip.com/search?q=방콕+미식+쿠킹클래스+패키지',
    tripComUrl: tripUrl('bangkok', 'bkk', 'g4'),
    rating: 4.6,
    personalityTypes: ['gourmet'],
    tags: ['미식', '방콕', '태국음식'],
  },
  // luxury 250만원~
  {
    id: 'g5',
    title: '나폴리+로마 7박9일 이탈리안 미식 (항공+숙박)',
    destination: '나폴리·로마',
    price: 3800000,
    priceRange: 'luxury',
    imageEmoji: '🍕',
    description: '인천↔로마 왕복 항공(직항) + 나폴리 3박·로마 4박 5성 호텔 + 피자·파스타 쿠킹 마스터클래스',
    myrealTripUrl: 'https://www.myrealtrip.com/search?q=이탈리아+나폴리+미식+패키지',
    tripComUrl: tripUrl('rome', 'fco', 'g5'),
    rating: 4.9,
    personalityTypes: ['gourmet'],
    tags: ['미식', '이탈리아', '쿠킹클래스'],
  },
  {
    id: 'g6',
    title: '리마+쿠스코 8박10일 페루 미식 기행 (항공+숙박)',
    destination: '페루',
    price: 5000000,
    priceRange: 'luxury',
    imageEmoji: '🦙',
    description: '인천↔리마 왕복 항공 + 세계 50대 레스토랑 디너 + 마추픽추 트레킹·리마 5성 호텔',
    myrealTripUrl: 'https://www.myrealtrip.com/search?q=페루+리마+미식+마추픽추+패키지',
    tripComUrl: tripUrl('lima', 'lim', 'g6'),
    rating: 4.8,
    personalityTypes: ['gourmet'],
    tags: ['미식', '페루', '남미'],
  },
];
